DROP DATABASE IF EXISTS tienda;
CREATE DATABASE IF NOT EXISTS tienda CHARACTER SET utf8 COLLATE utf8_general_ci;
USE tienda;

DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS VALORACIONES;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS STOCK;

CREATE TABLE IF NOT EXISTS USUARIO(
    Email VARCHAR(20) PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL,
    Apellido VARCHAR(20) NOT NULL,
    Fecha_naci DATE NOT NULL,
    Es_admin BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL,
    Estado ENUM('almacen','paqueteria', 'entregado'),
    Fecha DATE NOT NULL,
    Descripcion VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS VALORACIONES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Estrellas INT NOT NULL,
    Fecha DATE NOT NULL,
    Descripcion VARCHAR(50)
);